First implementation
polyswarm/parity pull request #1
Opened 2019-09-08 04:58 UTC by tagomaru

This was implemented to support `parity` for sidechain.

2019-09-10 18:28 UTC, mrtizmoatwork requested changes
a few minor changes

2019-09-10 18:28 UTC, mrtizmoatwork commented on .gitlab-ci.yml
> +  BASE_IMAGE_NAME: priv-testnet
this would be "parity"

2019-09-10 18:28 UTC, mrtizmoatwork commented on README.md
> +
this area should mention that this project is for parity client

2019-09-10 18:28 UTC, mrtizmoatwork commented on launch_parity_local.sh
> +DIR=$HOME/.ethereum/priv_testnet
this won't be "priv_testnet" anymore. should be "parity" or "parity_testnet" or something.

2019-09-11 19:52 UTC, tagomaru commented on launch_parity_local.sh
> +DIR=$HOME/.ethereum/priv_testnet
Sorry, but i forgot to delete this file.

2019-09-11 19:52 UTC, tagomaru commented on .gitlab-ci.yml
> +  BASE_IMAGE_NAME: priv-testnet
Yes, sorry.

2019-09-11 19:56 UTC, tagomaru commented on README.md
> +
ok

2019-09-11 21:02 UTC, mrtizmoatwork approved these changes
ok

2019-09-12 17:09 UTC, Rizato requested changes
Need to make the changes from this priv-testnet commit here. 

* adds a config.toml to start sealing blocks
* modified genesis.json to start in POA mode with a block per second
* sets up genesis.json to use tabs (it was mostly tabs, but some spaces)

https://github.com/polyswarm/priv-testnet/pull/7/commits/96fe052526f3893d48f2948f9cfeeffc4012ef86

The max size change I made in that commit is a mistake, though.

2019-09-16 13:31 UTC, Rizato approved these changes
lgtm

2019-09-24 13:22 UTC, merged